import { useEffect, useState } from "react";
import { api, post } from "./api";
import "./summary-jobs.css";
type Data = Record<string, any>;
const base = "/api/foundation/summary-jobs";
const states:Data={paused:"已暂停",running:"处理中",warning:"需核对",completed:"已完成",awaiting_agent:"等待外部Agent",budget_paused:"批次额度用完"};
const stages:Data={discover:"登记文件",inspect:"轻读分类",agent:"AI理解",markdown:"生成MD",done:"完成"};
const coverage:Data={partial:"内容抽样",signature_only:"仅文件签名",failed:"读取失败"};
const aiState:Data={pending:"待AI处理",not_requested:"本地处理",done:"AI已返回",rejected:"AI结果拒绝",unavailable:"无文字样本",stale:"来源已变化"};
const modes:Data={catalog:"仅保留位置与分类",extract:"本地摘录",full:"建立全文搜索",semantic:"全文搜索＋向量",recommended:"按 AI 建议混合处理"};
const importance:Data={high:"优先深入",normal:"常规",low:"低优先"};
const allInspectedId="__all_inspected__";
const sizes=(value:number)=>value<1024?`${value} B`:value<1024**2?`${(value/1024).toFixed(1)} KB`:value<1024**3?`${(value/1024**2).toFixed(1)} MB`:`${(value/1024**3).toFixed(1)} GB`;
const planUsesVector=(plan:Data|null)=>Number(plan?.actions?.semantic||0)>0;

function FileRow({file,categories,disabled,save}:{file:Data;categories:Data[];disabled:boolean;save:(id:number,v:Data)=>Promise<void>}) {
  const [category,setCategory]=useState(file.record?.classification?.category_id||"unresolved_other");
  const [summary,setSummary]=useState(file.summary?.text||"");
  const understanding=file.record?.understanding;
  useEffect(()=>{setCategory(file.record?.classification?.category_id||"unresolved_other");setSummary(file.summary?.text||"");},[file.id,file.revision]);
  return <tr><td>{file.record?.relative||file.path}<small>{coverage[file.record?.coverage]||"未读取"} · {aiState[file.ai_state]||file.ai_state}</small>
    <details><summary>AI理解、依据和样本</summary>{understanding&&<><p><strong>用途：</strong>{understanding.purpose}</p><p><strong>重要性：</strong>{importance[understanding.importance]||understanding.importance}；<strong>建议：</strong>{modes[understanding.recommended_mode]||understanding.recommended_mode}</p><p><strong>建议理由：</strong>{understanding.recommendation_reason}</p></>}<p><strong>证据：</strong>{file.summary?.evidence||file.record?.classification?.evidence?.join("、")||"暂无依据"}</p><p>{file.summary?.uncertainty}</p><p>{file.record?.text_preview}</p></details></td>
    <td><select aria-label={`任务分类 ${file.id}`} disabled={disabled||!file.record} value={category} onChange={e=>setCategory(e.target.value)}>{categories.filter(c=>c.parent_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{file.record?.classification?.secondary_categories?.length>0&&<small>辅助：{file.record.classification.secondary_categories.map((item:Data)=>item.label).join("、")}</small>}</td>
    <td><textarea aria-label={`文件摘要 ${file.id}`} disabled={disabled||!file.record} maxLength={2000} value={summary} onChange={e=>setSummary(e.target.value)}/><button disabled={disabled||!file.record} onClick={()=>save(file.id,{category_id:category,summary,revision:file.revision})}>保存修改</button></td></tr>;
}

function AssemblyTree({categories,counts,selected,onChange}:{categories:Data[];counts:Data[];selected:string[];onChange:(ids:string[])=>void}) {
  const parents=categories.filter(c=>!c.parent_id);
  const totals=new Map(counts.map(item=>[item.id,item]));
  const allInspected=totals.get(allInspectedId);
  const toggle=(id:string,checked:boolean)=>onChange(checked?[...new Set([...selected,id])]:selected.filter(item=>item!==id));
  return <div className="assembly-tree" role="tree">{allInspected&&<section className="assembly-branch"><label className="assembly-parent"><input type="checkbox" checked={selected.includes(allInspectedId)} onChange={e=>onChange(e.target.checked?[allInspectedId]:[])}/><span><strong>{allInspected.name}</strong><small>不按分类过滤；{Number(allInspected.count||0).toLocaleString()} 个已检查文件</small></span></label></section>}{parents.map(parent=>{const children=categories.filter(c=>c.parent_id===parent.id&&Number(totals.get(c.id)?.count||0)>0);if(!children.length)return null;const ids=children.map(c=>c.id);const checked=ids.every(id=>selected.includes(id));const partial=!checked&&ids.some(id=>selected.includes(id));return <section key={parent.id} className="assembly-branch">
    <label className="assembly-parent"><input type="checkbox" checked={checked} ref={node=>{if(node)node.indeterminate=partial;}} onChange={e=>onChange(e.target.checked?[...new Set([...selected,...ids])]:selected.filter(id=>!ids.includes(id)))}/><span><strong>{parent.name}</strong><small>{children.reduce((sum,c)=>sum+Number(totals.get(c.id)?.count||0),0).toLocaleString()} 个文件</small></span></label>
    <div>{children.map(child=>{const item=totals.get(child.id);return <label key={child.id} className={selected.includes(child.id)?"selected":""}><input type="checkbox" checked={selected.includes(child.id)} onChange={e=>toggle(child.id,e.target.checked)}/><span><strong>{child.name}</strong><small>{Number(item?.count||0).toLocaleString()} 个 · {sizes(Number(item?.bytes||0))}</small></span></label>})}</div>
  </section>})}</div>;
}

export default function SummaryJobsPanel({categories}:{categories:Data[]}) {
  const [path,setPath]=useState("");const [scope,setScope]=useState("catalog_batch");const [provider,setProvider]=useState("codex");const [consent,setConsent]=useState(false);
  const [model,setModel]=useState("gpt-5.6-luna");const [executable,setExecutable]=useState("");const [budget,setBudget]=useState(20);
  const [models,setModels]=useState<Data[]>([]);const [job,setJob]=useState<Data|null>(null);const [recent,setRecent]=useState<Data[]>([]);
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const [offset,setOffset]=useState(0);const [destination,setDestination]=useState("");
  const [selectedCategories,setSelectedCategories]=useState<string[]>([]);const [promotionMode,setPromotionMode]=useState("full");const [intake,setIntake]=useState<Data|null>(null);
  const [pipeline,setPipeline]=useState<Data>({catalog:0,classified:0,knowledge:0});
  const [catalogProgress,setCatalogProgress]=useState<Data>({});const [catalogBatch,setCatalogBatch]=useState(50);
  const [catalogCounts,setCatalogCounts]=useState<Data[]>([]);const [catalogSelected,setCatalogSelected]=useState<string[]>([]);const [catalogMode,setCatalogMode]=useState("full");const [catalogIntake,setCatalogIntake]=useState<Data|null>(null);
  const [catalogRecommendedIntake,setCatalogRecommendedIntake]=useState<Data|null>(null);
  const [autoPlan,setAutoPlan]=useState<Data|null>(null);
  const allClassified=catalogCounts.find(item=>item.id===allInspectedId);
  const recommendation=allClassified?.recommendations||{};
  const recommendedTotal=Number(recommendation.catalog||0)+Number(recommendation.extract||0)+Number(recommendation.full||0)+Number(recommendation.semantic||0);
  const reload=async(id:string,start=offset)=>{setJob((await api<Data>(`${base}/${id}?offset=${start}`)).data);};
  const perform=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  useEffect(()=>{api<Data[]>(base).then(async r=>{setRecent(r.data);const latest=r.data.find(item=>item.stage==="done");if(latest){setOffset(0);setJob((await api<Data>(`${base}/${latest.id}?offset=0`)).data);}}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{Promise.all([api<Data>("/api/foundation/machine-catalog"),api<Data>("/api/foundation/included-files?limit=1"),api<Data>(base+"/catalog-progress"),api<Data>(base+"/catalog-classifications"),api<Data|null>("/api/foundation/auto-promotion/latest"),api<Data[]>("/api/foundation/intake")]).then(async([catalog,knowledge,progress,classifications,latestPlan,intakes])=>{setPipeline((current:Data)=>({...current,catalog:Number(catalog.data?.catalog_files||0),knowledge:Number(knowledge.data?.total||0),classified:Number(progress.data?.inspected||0)}));setCatalogProgress(progress.data||{});setCatalogCounts(classifications.data?.counts||[]);setAutoPlan(latestPlan.data||null);const prepared=intakes.data.find(item=>item.state==="ready"&&item.request?.source_summary_job==="catalog-classification-ledger"&&item.request?.mode==="recommended");if(prepared)setCatalogRecommendedIntake((await api<Data>(`/api/foundation/intake/${prepared.id}`)).data);}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!job?.running)return;let active=true;const timer=setInterval(()=>{api<Data>(`${base}/${job.id}?offset=${offset}`).then(r=>{if(active)setJob(r.data);}).catch(e=>{if(active)setError(e.message);});},1500);return()=>{active=false;clearInterval(timer);};},[job?.id,job?.running,offset]);
  useEffect(()=>{setSelectedCategories([]);setIntake(null);},[job?.id]);
  useEffect(()=>{setCatalogRecommendedIntake(null);},[catalogSelected]);
  useEffect(()=>{if(!intake||!["scanning","backing_up","running"].includes(intake.state))return;let active=true;const timer=setInterval(()=>{api<Data>(`/api/foundation/intake/${intake.id}`).then(r=>{if(active)setIntake(r.data);}).catch(e=>{if(active)setError(e.message);});},1200);return()=>{active=false;clearInterval(timer);};},[intake?.id,intake?.state]);
  useEffect(()=>{if(!catalogIntake||!["scanning","backing_up","running"].includes(catalogIntake.state))return;let active=true;const timer=setInterval(()=>{api<Data>(`/api/foundation/intake/${catalogIntake.id}`).then(r=>{if(active)setCatalogIntake(r.data);}).catch(e=>{if(active)setError(e.message);});},1200);return()=>{active=false;clearInterval(timer);};},[catalogIntake?.id,catalogIntake?.state]);
  useEffect(()=>{if(!catalogRecommendedIntake||!["scanning","backing_up","running"].includes(catalogRecommendedIntake.state))return;let active=true;const timer=setInterval(()=>{api<Data>(`/api/foundation/intake/${catalogRecommendedIntake.id}`).then(r=>{if(active)setCatalogRecommendedIntake(r.data);}).catch(e=>{if(active)setError(e.message);});},1200);return()=>{active=false;clearInterval(timer);};},[catalogRecommendedIntake?.id,catalogRecommendedIntake?.state]);
  return <div className="foundation-panel summary-jobs"><section className="assembly-pipeline"><header><small>资料入库</small><h3>将已整理资料加入知识库</h3><p>这里是全盘分类结果的正式入口，不是新一轮扫描或摘要任务。</p></header><div className="pipeline-stages"><article><span>01 · A库轻索引</span><strong>{Number(pipeline.catalog||0).toLocaleString()}</strong><small>只记录路径、类型、大小和时间</small></article><i>筛选并轻读</i><article><span>02 · 已完成分类</span><strong>{Number(pipeline.classified||0).toLocaleString()}</strong><small>已写入跨批分类台账</small></article><i>勾选并确认</i><article><span>03 · 当前知识库</span><strong>{Number(pipeline.knowledge||0).toLocaleString()}</strong><small>正文、摘要或向量已可检索</small></article></div>{recommendedTotal>0&&<div className="append-only-policy"><strong>已有 {recommendedTotal.toLocaleString()} 份可装配候选</strong><span>L1 {Number(recommendation.extract||0).toLocaleString()} · L2 {Number(recommendation.full||0).toLocaleString()} · L3 {Number(recommendation.semantic||0).toLocaleString()}。下面选择分类后先看预览，再明确确认执行。</span></div>}<p className="pipeline-gap">A库不会把数百万条路径冒充成已理解知识。现在的AI速判会覆盖所有非临时文件；图片、压缩包、安装包等没有正文的资料也会进入“元数据速判”，不会被静默漏掉。</p><div className="append-only-policy"><strong>当前采用单向晋级</strong><span>索引 → AI速判 → 分类 → L1/L2/L3；普通操作只新增或升级。取消勾选不会移除已入库内容，旧版本保留用于追溯。</span></div></section>
  {catalogCounts.length>0&&<section className="promotion-panel catalog-assembly"><header><div><small>分类结果</small><h3>按分类结果加入知识库</h3><p>这里汇总所有已完成检查的A库批次；未分类、正在排队或读取失败的文件不会混进来。</p></div><span>{catalogSelected.length} 类已选择</span></header><div className="assembly-workbench"><AssemblyTree categories={categories} counts={catalogCounts} selected={catalogSelected} onChange={ids=>{setCatalogSelected(ids);setCatalogIntake(null);}}/><div className="assembly-settings"><label>加入知识库的程度<select aria-label="跨批分类后处理方式" value={catalogMode} onChange={e=>{setCatalogMode(e.target.value);setCatalogIntake(null);}}><option value="catalog">L0 · 仅保留位置与分类，不读正文</option><option value="extract">L1 · 本地摘录，保留来源与哈希</option><option value="full">L2 · 解析正文，支持全文搜索</option><option value="semantic">L3 · 全文搜索＋向量语义搜索</option></select></label><div className="assembly-selection"><span>预计选择</span><strong>{catalogCounts.filter(item=>catalogSelected.includes(item.id)).reduce((sum,item)=>sum+Number(item.count||0),0).toLocaleString()} 个文件</strong><small>{sizes(catalogCounts.filter(item=>catalogSelected.includes(item.id)).reduce((sum,item)=>sum+Number(item.bytes||0),0))}</small></div><p className="assembly-lock-note">分类台账只追加版本；此处的选择只决定本次新增或升级，不会删除已入库内容。</p><button className="assembly-preview-button" disabled={busy||catalogSelected.length===0} onClick={()=>perform(async()=>{const r=await post<Data>(base+"/catalog-promote-preview",{category_ids:catalogSelected,mode:catalogMode});setCatalogIntake(r.data);setNotice("跨批分类入库预览已生成，尚未写入知识库。");})}>检查并生成入库预览</button>{catalogIntake&&<div className="promotion-preview"><strong>执行前预览</strong><p>共 {catalogIntake.total} 个文件，{sizes(catalogIntake.source_bytes||0)}；可执行 {catalogIntake.counts.pending||0} 个，跳过 {catalogIntake.counts.skipped||0} 个。</p><p>{catalogIntake.note}</p>{!["completed","warning"].includes(catalogIntake.state)&&<button disabled={busy||catalogIntake.state!=="ready"} onClick={()=>perform(async()=>{const suffix=`?confirmed=true&confirmed_vector=${catalogMode==="semantic"}`;const r=await post<Data>(`/api/foundation/intake/${catalogIntake.id}/confirm${suffix}`,{});setCatalogIntake(r.data);setNotice(catalogMode==="semantic"?"已确认全文和向量处理。":"已确认执行。");})}>{catalogMode==="semantic"?"确认加入全文＋向量知识库":"确认加入知识库"}</button>}{["backing_up","running"].includes(catalogIntake.state)&&<span> 正在处理，可离开本页后再回来查看。</span>}</div>}</div></div></section>}
  {catalogCounts.length>0&&catalogSelected.length>0&&<section className="promotion-panel ai-recommended-assembly"><header><div><small>智能建议</small><h3>按 Luna 建议混合处理</h3><p>只采用已通过本地证据校验的 AI 理解档案：每份资料分别进入 L0、L1、L2 或 L3；没有可核验建议的资料会留在分类台账，不会被猜测性入库。</p></div></header><button className="assembly-preview-button" disabled={busy} onClick={()=>perform(async()=>{const r=await post<Data>(base+"/catalog-promote-preview",{category_ids:catalogSelected,mode:"recommended"});setCatalogRecommendedIntake(r.data);setNotice("AI建议混合入库预览已生成，尚未写入知识库。");})}>按 AI 建议生成混合预览</button>{catalogRecommendedIntake&&<div className="promotion-preview"><strong>混合处理预览</strong><p>共 {catalogRecommendedIntake.total} 个文件；L0 {catalogRecommendedIntake.actions?.catalog||0}，L1 {catalogRecommendedIntake.actions?.extract||0}，L2 {catalogRecommendedIntake.actions?.full||0}，L3 {catalogRecommendedIntake.actions?.semantic||0}。</p><p>{catalogRecommendedIntake.note}</p>{!["completed","warning"].includes(catalogRecommendedIntake.state)&&<button disabled={busy||catalogRecommendedIntake.state!=="ready"} onClick={()=>perform(async()=>{const suffix=`?confirmed=true&confirmed_vector=${planUsesVector(catalogRecommendedIntake)}`;const r=await post<Data>(`/api/foundation/intake/${catalogRecommendedIntake.id}/confirm${suffix}`,{});setCatalogRecommendedIntake(r.data);setNotice(planUsesVector(catalogRecommendedIntake)?"已确认混合处理，其中包含向量处理。":"已确认混合处理。");})}>{planUsesVector(catalogRecommendedIntake)?"确认按 AI 建议加入（含向量）":"确认按 AI 建议加入"}</button>}</div>}</section>}
  <h3>AI 整理电脑资料</h3>
    <p>本地逐文件轻读；可选择 Codex Luna 或 DeepSeek Flash 判断用途、分类并生成摘要。两者都必须通过同一套本地原文证据校验，不移动原文件。</p>
    <label>理解模型<select aria-label="资料理解模型" value={provider} onChange={e=>setProvider(e.target.value)}><option value="codex">Codex Luna（使用 Codex 额度）</option><option value="deepseek" disabled={scope==="auto_promotion_batch"}>DeepSeek Flash（使用 API 额度）</option></select></label>
    <label>整理范围<select aria-label="整理范围" value={scope} onChange={e=>{const next=e.target.value;setScope(next);if(next==="auto_promotion_batch")setProvider("codex");}}><option value="catalog_batch">从A库继续分类（推荐）</option><option value="auto_promotion_batch" disabled={!autoPlan}>按 Luna 全盘建议检查下一批</option><option value="all_local_drives">重新扫所有本地固定磁盘</option><option value="path">先测试一个指定目录</option></select></label>
    {scope==="catalog_batch"&&<><label>本批文件数<input aria-label="A库分类批次数" type="number" min={1} max={500} value={catalogBatch} onChange={e=>setCatalogBatch(Math.max(1,Math.min(500,Number(e.target.value)||1)))}/></label><p>A库已发现 {Number(catalogProgress.catalog_active||0).toLocaleString()} 个；AI已速判 {Number(catalogProgress.ai_done||0).toLocaleString()} 个；待速判 {Number(catalogProgress.ai_pending||0).toLocaleString()} 个；明确本地跳过 {Number(catalogProgress.local_skipped||0).toLocaleString()} 个。创建任务不会读取文件，点击开始后才会处理本批。</p></>}
    {scope==="auto_promotion_batch"&&autoPlan&&<><label>本批文件数<input aria-label="自动选择分类批次数" type="number" min={1} max={500} value={catalogBatch} onChange={e=>setCatalogBatch(Math.max(1,Math.min(500,Number(e.target.value)||1)))}/></label><p>使用最近完成的 Luna 目录建议：{Number(autoPlan.recommendation_counts?.needs_inspection||0).toLocaleString()} 个目录仍需逐文件检查。创建任务不会读取文件；开始后才会本地轻读本批，并以 Luna 复核分类。</p></>}
    {scope==="path"&&<label>资料目录<input aria-label="整理资料目录" value={path} onChange={e=>setPath(e.target.value)} placeholder="例如 E:\资料"/></label>}
    <label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>允许将文件的有限文字样本交给 {provider==="deepseek"?"DeepSeek":"Luna"}，可能消耗{provider==="deepseek"?" API":" Codex"}额度</label>
    <details><summary>高级设置</summary>{provider==="codex"&&<><label>Codex exe<input value={executable} onChange={e=>setExecutable(e.target.value)} placeholder="留空自动发现"/></label>
      <button disabled={busy} onClick={()=>perform(async()=>{const r=await post<Data>(base+"/probe",{executable});setModels(r.data.models);setNotice("连接成功，仅查询模型，未推理。");})}>检测Codex连接</button>
      <label>模型<input list="summary-models" value={model} onChange={e=>setModel(e.target.value)}/></label><datalist id="summary-models">{models.map(m=><option key={m.model} value={m.model}/>)}</datalist></>}
      <label>本轮最多AI批次<input type="number" min={1} max={10000} value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><p>{provider==="deepseek"?"DeepSeek 后备模式每批固定1文件，优先保证逐字证据可核对。":scope==="auto_promotion_batch"?"自动选择后的高价值资料固定每批1文件，避免一个结构异常拖累同包资料。":"Luna 新任务默认每批最多5文件。"}每文件最多2,000字样本；达到批次上限会暂停，可继续；不是免费API。</p></details>
    <button disabled={busy||!consent||(scope==="path"&&!path.trim())||(scope==="auto_promotion_batch"&&!autoPlan)} onClick={()=>perform(async()=>{const r=await post<Data>(base,{scope,path:path.trim(),provider,model:provider==="deepseek"?"deepseek-v4-flash":model,codex_executable:provider==="codex"?executable:"",allow_remote_processing:consent,batch_size:provider==="deepseek"||scope==="auto_promotion_batch"?1:5,max_ai_batches:budget,catalog_batch_size:catalogBatch,auto_promotion_id:scope==="auto_promotion_batch"?autoPlan?.id:""});setOffset(0);setJob(r.data);setRecent((await api<Data[]>(base)).data);const p=await api<Data>(base+"/catalog-progress");setCatalogProgress(p.data||{});})}>{scope==="catalog_batch"?"创建A库分类批次并开始":scope==="auto_promotion_batch"?"创建建议范围内的分类批次并开始":`开始 ${provider==="deepseek"?"DeepSeek":"Luna"} 整理`}</button>
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <label>恢复已有任务<select aria-label="恢复整理任务" value={job?.id||""} onChange={e=>{setOffset(0);if(e.target.value)void perform(()=>reload(e.target.value,0));}}><option value="">选择任务</option>{recent.map(r=><option key={r.id} value={r.id}>{r.root} · {states[r.state]||r.state} · {r.id.slice(0,8)}</option>)}</select></label>
    {job&&<><h3>{stages[job.stage]} · {states[job.state]||job.state}</h3><p>{job.message}</p>
      <p>已读 {job.counts.inspected||0}；待读 {job.counts.pending||0}；文件错误 {job.counts.error||0}；目录错误 {job.directory_errors}；排除 {job.excluded}。</p><p>AI已完成 {job.ai_counts.done||0}；待AI判断 {job.ai_counts.pending||0}；本地未请求 {job.ai_counts.not_requested||0}；AI结果拒绝 {job.ai_counts.rejected||0}；来源变化 {job.ai_counts.stale||0}。</p>
      <button disabled={busy||!job.running} onClick={()=>perform(async()=>{await post(`${base}/${job.id}/pause`,{});await reload(job.id);})}>暂停</button><button disabled={busy||job.running||job.stage==="done"} onClick={()=>perform(async()=>{await post(`${base}/${job.id}/resume`,{});await reload(job.id);})}>继续未完成部分</button>
      <button disabled={busy||job.running||!(job.counts.error||job.directory_errors||job.ai_counts.stale)} onClick={()=>perform(async()=>{await post(`${base}/${job.id}/retry-errors`,{});await reload(job.id);})}>重试读取异常</button>
      {job.roots?.length>0&&<details><summary>本次实际范围</summary><p>{job.roots.join("；")}</p></details>}
      {job.md_path&&<p>MD已生成：{job.md_path}</p>}
      {job.stage==="done"&&job.classification_counts?.length>0&&<section className="promotion-panel"><header><div><small>入库预览</small><h3>按分类组装知识库</h3><p>这里只显示当前分类任务的文件，不是全盘索引总量。左侧勾选内容，右侧决定搜索深度并预览。</p></div><span>{selectedCategories.length} 类已选择</span></header>
        <div className="assembly-workbench"><AssemblyTree categories={categories} counts={job.classification_counts} selected={selectedCategories} onChange={ids=>{setSelectedCategories(ids);setIntake(null);}}/><div className="assembly-settings">
          <label>加入知识库的程度<select aria-label="分类后处理方式" value={promotionMode} onChange={e=>{setPromotionMode(e.target.value);setIntake(null);}}><option value="catalog">L0 · 仅保留位置与分类，不读正文</option><option value="extract">L1 · 本地摘录，保留来源与哈希</option><option value="full">L2 · 解析正文，支持全文搜索</option><option value="semantic">L3 · 全文搜索＋向量语义搜索</option></select></label>
          <div className="assembly-mode-note"><strong>{promotionMode==="catalog"?"只建立资料地图":promotionMode==="extract"?"适合先建立可追溯的资料线索":promotionMode==="full"?"适合名称、编号和原句检索":"适合自然语言和近义表达检索"}</strong><p>{promotionMode==="catalog"?"不读取正文，也不会调用 Embedding。":promotionMode==="extract"?"只本地抽取少量原文片段，明确标注为未审核摘录；不调用 AI 或 Embedding。":promotionMode==="full"?"读取所选文件正文并分块，不调用 Embedding API。":"先解析全文，再调用 Embedding 服务生成向量；会产生对应 API 用量。"}</p></div>
          <div className="assembly-selection"><span>预计选择</span><strong>{job.classification_counts.filter((item:Data)=>selectedCategories.includes(item.id)).reduce((sum:number,item:Data)=>sum+Number(item.count||0),0).toLocaleString()} 个文件</strong><small>{sizes(job.classification_counts.filter((item:Data)=>selectedCategories.includes(item.id)).reduce((sum:number,item:Data)=>sum+Number(item.bytes||0),0))}</small></div><p className="assembly-lock-note">只增不减：本次未勾选或以后取消勾选，都不会删除已经进入知识库的内容。</p>
          <button className="assembly-preview-button" disabled={busy||selectedCategories.length===0} onClick={()=>perform(async()=>{const r=await post<Data>(`${base}/${job.id}/promote-preview`,{category_ids:selectedCategories,mode:promotionMode});setIntake(r.data);setNotice("处理预览已生成，尚未写入知识库。");})}>检查并生成入库预览</button>
          {intake&&<div className="promotion-preview"><strong>执行前预览</strong><p>共 {intake.total} 个文件，{sizes(intake.source_bytes||0)}；可执行 {intake.counts.pending||0} 个，跳过 {intake.counts.skipped||0} 个。</p><p>{intake.note}</p>
            {!["completed","warning"].includes(intake.state)&&<button disabled={busy||intake.state!=="ready"} onClick={()=>perform(async()=>{const suffix=`?confirmed=true&confirmed_vector=${promotionMode==="semantic"}`;const r=await post<Data>(`/api/foundation/intake/${intake.id}/confirm${suffix}`,{});setIntake(r.data);setNotice(promotionMode==="semantic"?"已确认全文和向量处理。":"已确认执行。");})}>{promotionMode==="semantic"?"确认加入全文＋向量知识库":"确认加入知识库"}</button>}
            {["backing_up","running"].includes(intake.state)&&<span> 正在处理，可离开本页后再回来查看。</span>}
            {["completed","warning"].includes(intake.state)&&<p role="status">{intake.state==="completed"?"处理完成。":"处理完成，但有文件跳过或失败，请查看接入记录。"}</p>}
          </div>}
        </div></div>
      </section>}
      <div className="foundation-scroll"><table><thead><tr><th>文件和依据</th><th>分类</th><th>摘要（可修改）</th></tr></thead><tbody>{job.records.map((f:Data)=><FileRow key={f.id} file={f} categories={categories} disabled={busy||job.running} save={(id,v)=>perform(async()=>{await post(`${base}/${job.id}/files/${id}`,v);await reload(job.id);})}/>)}</tbody></table></div>
      <button disabled={!offset||busy} onClick={()=>{const n=Math.max(0,offset-50);setOffset(n);void perform(()=>reload(job.id,n));}}>上一页</button><button disabled={job.records.length<50||busy} onClick={()=>{const n=offset+50;setOffset(n);void perform(()=>reload(job.id,n));}}>下一页</button>
      <label>导出目录 / Obsidian库目录<input aria-label="整理MD输出目录" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="已存在、位于源范围以外的目录"/></label><button disabled={busy||job.running||job.stage!=="done"||!destination} onClick={()=>perform(async()=>{const r=await post<Data>(`${base}/${job.id}/export`,{destination});setNotice("已生成MD目录："+r.data.path);})}>导出当前MD</button><p>每次导出新目录，不覆盖原有文件。Obsidian可直接读取这些标准MD。</p>
    </>}
  </div>;
}
